networks:
    laravel:
        driver: bridge
volumes:
    craftmate_db:
        driver: local

services:

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - craftmate_db:/var/lib/mysql
        environment:
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        networks:
            - laravel

    php:
        image: shinsenter/laravel:latest
        volumes:
            - ./:/var/www/html
        environment:
            PHP_DISPLAY_ERRORS: "1"
            PHP_POST_MAX_SIZE: "100M"
            PHP_UPLOAD_MAX_FILESIZE: "100M"
            PHP_SESSION_COOKIE_HTTPONLY: "1"
        ports:
            - "0.0.0.0:8000:80"
            - "8001:443"
            - "8002:443/udp"
        networks:
            - laravel
        depends_on:
            - phpmyadmin

    phpmyadmin:
        image: 'phpmyadmin:latest'
        restart: unless-stopped
        ports:
            - '8080:80'
        networks:
            - laravel
        environment:
            PMA_HOST: mariadb
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'

